# Generated by Django 3.1.4 on 2020-12-20 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Book', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('main_image', models.ImageField(max_length=32000, null=True, upload_to='')),
                ('original_release', models.DateField(null=True)),
                ('author', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Vinyl Record', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('main_image', models.ImageField(max_length=32000, null=True, upload_to='')),
                ('original_release', models.DateField(null=True)),
                ('artist', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='System', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('main_image', models.ImageField(max_length=32000, null=True, upload_to='')),
                ('original_release', models.DateField(null=True)),
                ('manufacturer', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, default='Game', max_length=100)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('main_image', models.ImageField(max_length=32000, null=True, upload_to='')),
                ('original_release', models.DateField(null=True)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.system')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.blogcategory')),
            ],
        ),
    ]
